### ISSUE TITLE
.xz file not work

### ISSUE THREAD

**Issue by jianshu93** [dnbaker/dashing2-binaries#1]
Hello Daniel,
it is really strange:

(base) $ unxz -d dashing2_s512bw.xz 
unxz: dashing2_s512bw.xz: File format not recognized

Any idea why?

Thanks,

Jianshu

**Comment by dnbaker** [comment]
Hi Jianshu -

I'll look into this tonight and get it fixed. Sorry for the trouble, and thanks for letting me know.

**Comment by dnbaker** [comment]
Hi Jianshu,

Would you please let me know which version you're downloading, and try downloading again?
I haven't been able to reproduce a decompression error on my end, but maybe there's something extra wrong with it.

Thanks,

Daniel

**Comment by jianshu93** [comment]
https://github.com/dnbaker/dashing2-binaries/blob/main/linux/v2.1.6/dashing2_s512bw.xz

on linux

Jianshu

**Comment by dnbaker** [comment]
Hi Jianshu,

I downloaded that link directly, which yielded a file I couldn't open with xz, but I can download the raw file (Path https://github.com/dnbaker/dashing2-binaries/blob/main/linux/v2.1.6/dashing2_s512bw.xz?raw=true, for instance).

If I leave out the "?raw=true", I end up downloading some kind of html document that can't be opened with xz. Maybe that's what happened to you?

In case it's convenient, you can download, decompress, and prepare for use by:

`wget https://github.com/dnbaker/dashing2-binaries/blob/main/linux/v2.1.6/dashing2_s512bw.xz?raw=true && mv dashing2_s512bw.xz?raw=true dashing2_s512bw.xz && xz -d dashing2_s512bw.xz && chmod 755 dashing2_s512bw`

Would you give that a shot?

**Comment by jianshu93** [comment]
It works!! Its really strange

Jianshu

**Comment by jianshu93** [comment]
I download using wget for the .xz file you provided (now raw). May be git clone instead? Sorry for that I developed a habit of using wget for binaries because most of the time owners release a package. I have have problem with that routine, but I did not realize this is a github page.

Many thanks!


Jianshu

**Comment by dnbaker** [comment]
It's good feedback for me - I want to make the process as streamlined as possible. In particular, I'll probably put together a new set of links for easy download into the main README.md.

Thank you, really - this should make it easier for others to get started.
